name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i --legacy-peer-deps
    - run: npm run build
      env:
        CI: false

    - name: Publish to Cloudflare Pages
      uses: sctg-development/pages-action-without-url@main
      with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
            directory: build # e.g. 'dist'
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}